# A sample Gemfile
source "https://rubygems.org"

gem "em-websocket"
gem "twitter"
gem "sqlite3"
gem "activerecord"
gem "activesupport"

gem "terminal-notifier" if RUBY_PLATFORM.match(/darwin/)

group :development do
  gem "pry"
  gem "pry-byebug"
  gem "pry-coolline"
end
