# A sample Gemfile
source "https://rubygems.org"

ruby "2.1.2"

gem "em-websocket"
gem "twitter"
gem "sqlite3"
gem "activerecord"
gem "activesupport"

group :development do
  gem "pry"
  gem "pry-byebug"
  gem "pry-coolline"
end
